services:
  app:
    ports:
      - "8080:8080"
    volumes:
      - ./config/application-secret.yaml:/app/config/application-secret.yaml
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_CONFIG_IMPORT=file:/app/config/application-secret.yaml
    env_file:
      - .env.production
    extends:
      file: docker-compose.yaml
      service: app
  db:
    env_file:
      - .env.production
    extends:
      file: docker-compose.yaml
      service: db
volumes:
  db-data:
