version: "3.8"
services:
  app:
    container_name: invest72-app
    image: nemo1107/invest72-app:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    networks:
      - default
  db:
    container_name: invest72-db
    image: postgres:17.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - default
networks:
  default:
    driver: bridge
