spring:
  profiles:
    group:
      local: local, secret
      production: production, secret
      test: test, secret
    default: local
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:invest72}
    username: ${POSTGRES_USER:invest72}
    password: ${POSTGRES_PASSWORD:invest72}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # 실행되는 SQL을 콘솔에 보기 좋게 출력
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true # 기존 DB에 Flyway를 처음 적용할 때 히스토리 테이블(flyway_schema_history)을 생성하고 동기화
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
