spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        show_sql: false
app:
  oauth2:
    authorized-redirect-uri: https://invest72.web.app/ # Firebase Hosting 주소
