spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        show_sql: false
app:
  oauth2:
    authorized-redirect-uri: https://www.invest72.site # Firebase Hosting 주소
