spring:
  profiles:
    group:
      local: local, secret
      production: production, secret
      test: test, secret
    default: local
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:invest72}
    username: ${POSTGRES_USER:invest72}
    password: ${POSTGRES_PASSWORD:invest72}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # 실행되는 SQL을 콘솔에 보기 좋게 출력
        format_sql: true
    show-sql: true


